### PR TITLE
WIP examine vectorization behaviour of CRAY and GNU compilers

### PR DESCRIPTION
**Pull request by sekelle**

### CODE REVIEW

**Comment by jgphpc** [comment]
The raw code is https://github.com/eth-cscs/examples_cpp/tree/jg%2Bseb/Code/Vector3D/slow1

**Comment by mbianco** [comment]
shouldn't the PR include the sources and maybe exclude the listings that are generated files? Or do you want them for historical reasdons?

**Comment by sebkelle1** [comment]
Yes, I don't know why you can't see them. I just checkout out the branch, added one directory and pushed.

**Comment by sebkelle1** [comment]
So, the sources are already there in `eth-cscs:jg+seb`

**Pull request closed without merging**
